### ISSUE TITLE
mention the alignment server in the readme

### ISSUE THREAD

**Issue by yochannah** [intermine/bluegenes-msa-viewer#8]
hey all - this is looking great! It took a little digging through chat logs to figure out how to run the sequence alignment server - can y'all add docs for it to this repo readme, e.g. what to clone and what settings to change here (if anything?)

**Comment by akshatbhargava123** [comment]
Thanks for pointing out, assigned to myself.

**Comment by heralden** [comment]
I see that this has been added. Closing...
